sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1925392412
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-take-out-wangyulong
  redis:
    port: 6379
    host: localhost
    database: 0
  wechat:
    appid: wx394dca0faee07e22
    secret: e1c4c9a96e32f453888480a7a2e0b274
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    refundNotifyUrl: